### ISSUE TITLE
Size mismatching error occurs when sampling.

### ISSUE THREAD

**Issue by zhouxiangxin1998** [harryjo97/GDSS#7]
Run`CUDA_VISIBLE_DEVICES=0 python main.py --type sample --config sample`.
The output is as the following, an error about size mismatching occurs:
```
./checkpoints/ZINC250k/gdss_zinc250k.pth loaded
----------------------------------------------------------------------------------------------------
Make Directory ZINC250k/test in Logs
----------------------------------------------------------------------------------------------------
[ZINC250k]   init=atom (9)   seed=42   batch_size=1024
----------------------------------------------------------------------------------------------------
lr=0.005 schedule=True ema=0.999 epochs=1000 reduce=False eps=1e-05
(ScoreNetworkX)+(ScoreNetworkA=GCN,4)   : depth=2 adim=16 nhid=16 layers=6 linears=3 c=(2 8 4)
(x:VP)=(0.10, 1.00) N=1000 (adj:VE)=(0.20, 1.00) N=1000
----------------------------------------------------------------------------------------------------
(Reverse)+(Langevin): eps=0.0001 denoise=True ema=False || snr=0.2 seps=0.9 n_steps=1
----------------------------------------------------------------------------------------------------
GEN SEED: 42


Loading file ./data/zinc250k_kekulized.npz
Number of training mols: 224568 | Number of test mols: 24887
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    main(work_type_parser.parse_known_args()[0])
  File "main.py", line 30, in main
    sampler.sample()
  File "/root/projects/GDSS/sampler.py", line 129, in sample
    x, adj, _ = self.sampling_fn(self.model_x, self.model_adj, self.init_flags)
  File "/root/projects/GDSS/solver.py", line 177, in pc_sampler
    x = mask_x(x, flags)
  File "/root/projects/GDSS/utils/graph_utils.py", line 12, in mask_x
    return x * flags[:,:,None]
RuntimeError: The size of tensor a (3000) must match the size of tensor b (10000) at non-singleton dimension 0
```

**Comment by harryjo97** [comment]
Thank you for finding the error!
The size mismatch was due to the tensor size mismatch between the initial flags and the generated molecules.
I have fixed the method `load_sampling_fn` in `utils/loader.py` to generate 10,000 molecules, and it works well now.
